project:
  type: website
  output-dir: docs
  resources: 
    - "docs"
  render:
    - "*.qmd"
    - "!docs/"  # docsフォルダの中身は無視してね、という指示
  
website:
  title: "Takenori Konaka's Page"
  navbar:
    background: orange
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: notes.qmd
        text: Notes
      - href: projects.qmd
        text: Projects
    tools:
      - icon: twitter-x
        href: https://x.com/KonakaTakenori
      - icon: github
        href: https://github.com/TakenoriKonaka
  page-footer:
    left: "&copy; Copyright 2024, Takenori Konaka"

format:
  html:
    theme: simplex
    toc: true

editor: source

