project:
  type: website
  output-dir: docs
  
website:
  title: "Takenori Konaka's Page"
  navbar:
    background: orange
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
      - href: notes.qmd
      - href: projects.qmd
    tools:
      - icon: x
        href: https://x.com/KonakaTakenori
      - icon: github
        href: https://github.com/TakenoriKonaka
  page-footer:
    left: "&copy; Copyright 2024, Takenori Konaka"

format:
  html:
    theme: simplex
    toc: true

editor: source

